name: Build Boost, talloc, proot for Android ARM64 (bionic, ananbox compatible)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-all:
    runs-on: ubuntu-22.04 # Закрепляем версию раннера для стабильности кэша

    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Установка зависимостей (инструменты хоста)
      - name: Install dependencies (host tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget bzip2 tar build-essential ninja-build unzip git python3 curl autoconf automake libtool pkg-config

      # Кэширование Android NDK
      - name: Cache Android NDK
        id: cache-ndk
        uses: actions/cache@v4
        with:
          path: $HOME/android-ndk
          key: ndk-r26c-${{ runner.os }}

      # Загрузка и распаковка Android NDK (r26c)
      - name: Download and extract Android NDK (r26c)
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26c-linux.zip -O ndk.zip
          unzip -q ndk.zip
          mv android-ndk-r26c $HOME/android-ndk

      # Проверка целостности Android NDK
      - name: Verify Android NDK integrity
        run: |
          if [ ! -f "$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" ]; then
            echo "Error: NDK toolchain is incomplete, aarch64-linux-android21-clang not found"
            exit 1
          fi
          ls -l $HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin
          ls -l $HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android
          ls -l $HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
          file $HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang

      # Настройка окружения Android NDK
      - name: Set up Android NDK environment
        run: |
          echo "ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

      # --- BOOST ---
      - name: Prepare Boost download script
        run: |
          cat <<'EOF' > download_boost.sh
          #!/bin/bash
          BOOST_URL="$1"
          BOOST_ARCHIVE="$2"
          MAX_ATTEMPTS=5
          for attempt in $(seq 1 $MAX_ATTEMPTS); do
              echo "Attempt $attempt of $MAX_ATTEMPTS"
              curl -L --progress-bar -o "$BOOST_ARCHIVE" "$BOOST_URL"
              if [ $? -eq 0 ] && [ -s "$BOOST_ARCHIVE" ]; then
                  echo "Download successful."
                  exit 0
              else
                  echo "Download failed, retrying..."
                  sleep 3
              fi
          done
          echo "Failed to download Boost after $MAX_ATTEMPTS attempts."
          exit 1
          EOF
          chmod +x download_boost.sh

      - name: Download Boost source (GitHub mirror, with progress & retry)
        run: |
          ./download_boost.sh "https://github.com/boostorg/boost/releases/download/boost-1.83.0/boost-1.83.0.tar.xz" "boost-1.83.0.tar.xz"
          tar -xf boost-1.83.0.tar.xz
          mv boost-1.83.0 boost_1_83_0

      - name: List files after extracting Boost
        run: ls -lah

      - name: Prepare user-config.jam for Boost (Android arm64-v8a)
        run: |
          ANDROID_API=21
          NDK_HOME="$HOME/android-ndk"
          TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          echo "using clang : android : $TOOLCHAIN/clang++ --target=aarch64-linux-android$ANDROID_API --sysroot=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot ;" > $HOME/user-config.jam

      - name: Bootstrap Boost.Build
        working-directory: ./boost_1_83_0
        run: |
          ./bootstrap.sh --with-toolset=clang

      - name: Build Boost for Android arm64-v8a (bionic, only needed libs)
        working-directory: ./boost_1_83_0
        env:
          ANDROID_API: 21
          NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          SYSROOT="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
          ./b2 toolset=clang-android \
            cxxflags="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -std=c++14 -fvisibility=hidden" \
            linkflags="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -pie -Wl,--no-undefined -std=c++14" \
            target-os=android \
            address-model=64 \
            architecture=arm \
            abi=aapcs \
            binary-format=elf \
            threading=multi \
            threadapi=pthread \
            variant=release \
            link=static,shared \
            runtime-link=shared \
            --prefix=../boost_android_arm64_install \
            --build-dir=../boost_android_arm64_build \
            --layout=system \
            --user-config=$HOME/user-config.jam \
            --with-date_time \
            --with-filesystem \
            --with-log \
            --with-program_options \
            --with-regex \
            --with-serialization \
            --with-system \
            --with-thread \
            -d+2 install -j$(nproc) > boost_build.log 2>&1

      - name: Package Boost artifacts
        run: |
          tar -czvf boost_android_arm64.tar.gz -C boost_android_arm64_install .

      - name: Upload Boost build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: boost-build-log
          path: boost_1_83_0/boost_build.log

      - name: Upload Boost artifact
        uses: actions/upload-artifact@v4
        with:
          name: boost_android_arm64
          path: boost_android_arm64.tar.gz

      # --- TALLOC ---
      - name: Download and extract talloc
        run: |
          wget https://www.samba.org/ftp/talloc/talloc-2.4.1.tar.gz -O talloc-2.4.1.tar.gz
          tar -xf talloc-2.4.1.tar.gz
          ls -lah talloc-2.4.1

      - name: Create talloc cross-answers.txt
        run: |
          cat << EOF > talloc-2.4.1/cross-answers.txt
          Checking uname sysname type: "Linux"
          Checking uname machine type: "dontcare"
          Checking uname release type: "dontcare"
          Checking uname version type: "dontcare"
          Checking simple C program: OK
          rpath library support: OK
          -Wl,--version-script support: FAIL
          Checking getconf LFS_CFLAGS: OK
          Checking for large file support without additional flags: OK
          Checking for -D_FILE_OFFSET_BITS=64: OK
          Checking for -D_LARGE_FILES: OK
          Checking correct behavior of strtoll: OK
          Checking for working strptime: OK
          Checking for C99 vsnprintf: OK
          Checking for HAVE_SHARED_MMAP: OK
          Checking for HAVE_MREMAP: OK
          Checking for HAVE_INCOHERENT_MMAP: OK
          Checking for HAVE_SECURE_MKSTEMP: OK
          Checking getconf large file support flags work: OK
          Checking for HAVE_IFACE_IFCONF: FAIL
          EOF

      - name: Patch talloc configure for cross-compilation and disable build tests
        run: |
          cd talloc-2.4.1
          if [ -f wscript ]; then
            sed -i 's/enable_build_tests=yes/enable_build_tests=no/g' wscript
          fi
          export ac_cv_func_malloc_0_nonnull=yes
          export ac_cv_func_realloc_0_nonnull=yes
          export ac_cv_func_memcmp_working=yes

      - name: Configure and build talloc for Android arm64-v8a (autotools)
        run: |
          export ANDROID_API=21
          export NDK_HOME="$HOME/android-ndk"
          export TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export SYSROOT="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
          export CC="$TOOLCHAIN/aarch64-linux-android$ANDROID_API-clang"
          export AR="$TOOLCHAIN/llvm-ar"
          export RANLIB="$TOOLCHAIN/llvm-ranlib"
          export CFLAGS="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC"
          export LDFLAGS="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC"
          cd talloc-2.4.1
          ./configure --host=aarch64-linux-android --prefix=$PWD/install --disable-python --without-gettext --disable-rpath \
            --cross-compile --cross-answers=$PWD/cross-answers.txt \
            CC="$CC" AR="$AR" RANLIB="$RANLIB" CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" \
            ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes ac_cv_func_memcmp_working=yes > configure.log 2>&1
          make V=1 -j$(nproc) > make.log 2>&1
          make install > make_install.log 2>&1

      - name: Verify talloc install
        run: |
          ls -l talloc-2.4.1/install/lib
          ls -l talloc-2.4.1/install/include

      - name: Package talloc artifacts
        run: |
          tar -czvf talloc_android_arm64.tar.gz -C talloc-2.4.1/install .

      - name: Upload talloc logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: talign:build-logs
          path: |
            talloc-2.4.1/config.log
            talloc-2.4.1/bin/config.log
            talloc-2.4.1/configure.log
            talloc-2.4.1/make.log
            talloc-2.4.1/make_install.log

      - name: Upload talloc artifact
        uses: actions/upload-artifact@v4
        with:
          name: talloc_android_arm64
          path: talloc_android_arm64.tar.gz

      # --- PROOT ---
      - name: Clone proot
        run: |
          git clone --depth=1 https://github.com/Ananbox/proot.git proot

      - name: Build proot for Android arm64-v8a (with talloc)
        run: |
          export ANDROID_API=21
          export NDK_HOME="$HOME/android-ndk"
          export TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export SYSROOT="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
          export CC="$TOOLCHAIN/aarch64-linux-android$ANDROID_API-clang"
          export AR="$TOOLCHAIN/llvm-ar"
          export RANLIB="$TOOLCHAIN/llvm-ranlib"
          export CFLAGS="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -I$PWD/talloc-2.4.1/install/include"
          export LDFLAGS="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -L$PWD/talloc-2.4.1/install/lib -ltalloc"
          cd proot/src
          make clean > make_clean.log 2>&1
          make V=1 CC="$CC" LD="$CC" STRIP=echo OBJCOPY=echo OBJDUMP=echo CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" > make.log 2>&1
          cp -v proot $GITHUB_WORKSPACE/libproot.so

      - name: Package proot artifacts
        run: |
          tar -czvf proot_android_arm64.tar.gz libproot.so

      - name: Upload proot logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: proot-build-logs
          path: |
            proot/src/make_clean.log
            proot/src/make.log

      - name: Upload proot artifact
        uses: actions/upload-artifact@v4
        with:
          name: proot_android_arm64
          path: proot_android_arm64.tar.gz
