name: Build Boost for ARMv8 (Clang, ARM64 sysroot .so from archive)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-boost-armv8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm lld gcc-aarch64-linux-gnu g++-aarch64-linux-gnu zstd wget bzip2 tar build-essential

      - name: Extract ARM64 .so libs from data.tar.zst
        run: |
          mkdir -p /tmp/arm64libs
          tar --use-compress-program=unzstd -xf data.tar.zst -C /tmp/arm64libs \
            ./usr/lib/aarch64-linux-gnu/libc.so.6 \
            ./usr/lib/aarch64-linux-gnu/libm.so.6 \
            ./usr/lib/aarch64-linux-gnu/libmvec.so.1 \
            ./usr/lib/aarch64-linux-gnu/libpthread.so.0 \
            ./usr/lib/aarch64-linux-gnu/librt.so.1 \
            ./usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1
          sudo mkdir -p /usr/aarch64-linux-gnu/lib/
          sudo cp /tmp/arm64libs/usr/lib/aarch64-linux-gnu/libc.so.6 /usr/aarch64-linux-gnu/lib/
          sudo cp /tmp/arm64libs/usr/lib/aarch64-linux-gnu/libm.so.6 /usr/aarch64-linux-gnu/lib/
          sudo cp /tmp/arm64libs/usr/lib/aarch64-linux-gnu/libmvec.so.1 /usr/aarch64-linux-gnu/lib/
          sudo cp /tmp/arm64libs/usr/lib/aarch64-linux-gnu/libpthread.so.0 /usr/aarch64-linux-gnu/lib/
          sudo cp /tmp/arm64libs/usr/lib/aarch64-linux-gnu/librt.so.1 /usr/aarch64-linux-gnu/lib/
          sudo cp /tmp/arm64libs/usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1 /usr/aarch64-linux-gnu/lib/
          ls -lh /usr/aarch64-linux-gnu/lib/
          file /usr/aarch64-linux-gnu/lib/libm.so.6

      - name: Download Boost source
        run: |
          wget -nv https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2/download -O boost_1_83_0.tar.bz2
          tar -xf boost_1_83_0.tar.bz2

      - name: Prepare user-config.jam for Clang ARM
        run: |
          echo "using clang : arm : clang++ -target aarch64-linux-gnu --sysroot=/usr/aarch64-linux-gnu ;" > $HOME/user-config.jam

      - name: Bootstrap Boost.Build
        working-directory: ./boost_1_83_0
        run: |
          ./bootstrap.sh --with-toolset=clang

      - name: Build Boost for ARMv8/ARMv9 (Clang, ARM sysroot)
        working-directory: ./boost_1_83_0
        run: |
          ./b2 toolset=clang-arm \
            cxxflags="-target aarch64-linux-gnu --sysroot=/usr/aarch64-linux-gnu -march=armv8-a -fPIC -std=c++14" \
            linkflags="--target=aarch64-linux-gnu --sysroot=/usr/aarch64-linux-gnu -fuse-ld=lld" \
            variant=release \
            threading=multi \
            link=static,shared \
            runtime-link=shared \
            --prefix=../boost_armv8_clang_install \
            --build-dir=../boost_armv8_clang_build \
            --user-config=$HOME/user-config.jam \
            --with-filesystem \
            --with-log \
            --with-serialization \
            --with-system \
            --with-thread \
            --with-program_options \
            install -j$(nproc)

      - name: Diagnostics (list built libs)
        run: |
          find boost_armv8_clang_install -type f

      - name: Package Boost artifacts
        run: |
          tar -czvf boost_armv8_clang.tar.gz boost_armv8_clang_install

      - name: Upload Boost artifact
        uses: actions/upload-artifact@v4
        with:
          name: boost_armv8_clang
          path: boost_armv8_clang.tar.gz
