name: Build Boost, talloc, proot for Android ARM64 (bionic, ananbox compatible)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (host tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget bzip2 tar build-essential ninja-build unzip git python3 curl autoconf automake libtool pkg-config

      - name: Download and extract Android NDK (r26c)
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26c-linux.zip -O ndk.zip
          unzip -q ndk.zip
          mv android-ndk-r26c $HOME/android-ndk

      - name: Set up Android NDK environment
        run: |
          echo "ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

      # --- BOOST ---
      - name: Prepare Boost download script
        run: |
          cat <<'EOF' > download_boost.sh
          #!/bin/bash
          BOOST_URL="$1"
          BOOST_ARCHIVE="$2"
          MAX_ATTEMPTS=5
          for attempt in $(seq 1 $MAX_ATTEMPTS); do
              echo "Attempt $attempt of $MAX_ATTEMPTS"
              curl -L --progress-bar -o "$BOOST_ARCHIVE" "$BOOST_URL"
              if [ $? -eq 0 ] && [ -s "$BOOST_ARCHIVE" ]; then
                  echo "Download successful."
                  exit 0
              else
                  echo "Download failed, retrying..."
                  sleep 3
              fi
          done
          echo "Failed to download Boost after $MAX_ATTEMPTS attempts."
          exit 1
          EOF
          chmod +x download_boost.sh

      - name: Download Boost source (GitHub mirror, with progress & retry)
        run: |
          ./download_boost.sh "https://github.com/boostorg/boost/releases/download/boost-1.83.0/boost-1.83.0.tar.xz" "boost-1.83.0.tar.xz"
          tar -xf boost-1.83.0.tar.xz
          mv boost-1.83.0 boost_1_83_0

      - name: List files after extracting Boost
        run: ls -lah

      - name: Prepare user-config.jam for Boost (Android arm64-v8a)
        run: |
          ANDROID_API=21
          NDK_HOME="$HOME/android-ndk"
          TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          echo "using clang : android : $TOOLCHAIN/clang++ --target=aarch64-linux-android$ANDROID_API --sysroot=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot ;" > $HOME/user-config.jam

      - name: Bootstrap Boost.Build
        working-directory: ./boost_1_83_0
        run: |
          ./bootstrap.sh --with-toolset=clang

      - name: Build Boost for Android arm64-v8a (bionic, only needed libs)
        working-directory: ./boost_1_83_0
        env:
          ANDROID_API: 21
          NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          SYSROOT="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
          ./b2 toolset=clang-android \
            cxxflags="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -std=c++14 -fvisibility=hidden" \
            linkflags="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -pie -Wl,--no-undefined -std=c++14" \
            target-os=android \
            address-model=64 \
            architecture=arm \
            abi=aapcs \
            binary-format=elf \
            threading=multi \
            threadapi=pthread \
            variant=release \
            link=static,shared \
            runtime-link=shared \
            --prefix=../boost_android_arm64_install \
            --build-dir=../boost_android_arm64_build \
            --layout=system \
            --user-config=$HOME/user-config.jam \
            --with-date_time \
            --with-filesystem \
            --with-log \
            --with-program_options \
            --with-regex \
            --with-serialization \
            --with-system \
            --with-thread \
            -d+2 install -j$(nproc)

      - name: Package Boost artifacts
        if: success()
        run: |
          tar -czvf boost_android_arm64.tar.gz boost_android_arm64_install

      # --- TALLOC ---
      - name: Download and extract talloc
        run: |
          wget https://www.samba.org/ftp/talloc/talloc-2.4.1.tar.gz -O talloc-2.4.1.tar.gz
          tar -xf talloc-2.4.1.tar.gz
          ls -lah talloc-2.4.1

      - name: Patch talloc configure for cross-compilation and disable build tests
        run: |
          # Some versions of talloc's configure/waf try to run cross-built binaries for feature detection (which fails).
          # Patch configure to force assume working functions, skip program runs, and disable build tests.
          cd talloc-2.4.1
          sed -i 's/enable_build_tests=yes/enable_build_tests=no/g' wscript
          # Also forcibly set config variables if needed (for old waf)
          export ac_cv_func_malloc_0_nonnull=yes
          export ac_cv_func_realloc_0_nonnull=yes
          export ac_cv_func_memcmp_working=yes

      - name: Configure and build talloc for Android arm64-v8a (autotools)
        continue-on-error: true
        run: |
          export ANDROID_API=21
          export NDK_HOME="$HOME/android-ndk"
          export TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export SYSROOT="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
          export CC="$TOOLCHAIN/aarch64-linux-android$ANDROID_API-clang"
          export AR="$TOOLCHAIN/llvm-ar"
          export RANLIB="$TOOLCHAIN/llvm-ranlib"
          export CFLAGS="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC"
          export LDFLAGS="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC"
          cd talloc-2.4.1
          ./configure --host=aarch64-linux-android --prefix=$PWD/install --disable-python --without-gettext --disable-rpath \
            CC="$CC" AR="$AR" RANLIB="$RANLIB" CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" \
            ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes ac_cv_func_memcmp_working=yes || true
          make -j$(nproc) || true
          make install || true

      - name: Upload config.log if talloc build fails
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: talloc-config-log
          path: |
            talloc-2.4.1/bin/config.log
            talloc-2.4.1/config.log

      - name: Package talloc artifacts
        if: success()
        run: |
          tar -czvf talloc_android_arm64.tar.gz -C talloc-2.4.1/install .

      # --- PROOT ---
      - name: Clone proot
        run: |
          git clone --depth=1 https://github.com/Ananbox/proot.git proot

      - name: Build proot for Android arm64-v8a (with talloc)
        run: |
          export ANDROID_API=21
          export NDK_HOME="$HOME/android-ndk"
          export TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export SYSROOT="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
          export CC="$TOOLCHAIN/aarch64-linux-android$ANDROID_API-clang"
          export AR="$TOOLCHAIN/llvm-ar"
          export RANLIB="$TOOLCHAIN/llvm-ranlib"
          export CFLAGS="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -I$PWD/talloc-2.4.1/install/include"
          export LDFLAGS="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -L$PWD/talloc-2.4.1/install/lib -ltalloc"
          cd proot/src
          make clean
          make V=1 CC="$CC" LD="$CC" STRIP=echo OBJCOPY=echo OBJDUMP=echo CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS"
          cp -v proot $GITHUB_WORKSPACE/libproot.so

      - name: Package proot artifacts
        if: success()
        run: |
          tar -czvf proot_android_arm64.tar.gz libproot.so

      # --- FINAL ARTIFACTS ---
      - name: Upload Boost artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: boost_android_arm64
          path: boost_android_arm64.tar.gz

      - name: Upload talloc artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: talloc_android_arm64
          path: talloc_android_arm64.tar.gz

      - name: Upload proot artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: proot_android_arm64
          path: proot_android_arm64.tar.gz
