name: Build Boost, talloc, proot for Android ARM64 (bionic, ananbox compatible)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-all:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (host tools)
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y wget bzip2 tar build-essential ninja-build unzip \
            git python3 curl autoconf automake libtool pkg-config patch

      - name: Cache Android NDK
        id: cache-ndk
        uses: actions/cache@v4
        with:
          path: $HOME/android-ndk
          key: ndk-r26c-${{ runner.os }}

      - name: Download and extract Android NDK (r26c)
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: |
          set -e
          wget https://dl.google.com/android/repository/android-ndk-r26c-linux.zip -O ndk.zip
          unzip -q ndk.zip
          mv android-ndk-r26c $HOME/android-ndk

      - name: Set up Android NDK environment
        run: |
          echo "ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

      # --- BOOST ---
      - name: Download Boost source
        run: |
          set -e
          wget -O boost-1.83.0.tar.xz https://github.com/boostorg/boost/releases/download/boost-1.83.0/boost-1.83.0.tar.xz
          tar -xf boost-1.83.0.tar.xz
          mv boost-1.83.0 boost_1_83_0

      - name: Prepare user-config.jam for Boost
        run: |
          set -e
          ANDROID_API=21
          NDK_HOME="$HOME/android-ndk"
          TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          echo "using clang : android : $TOOLCHAIN/clang++ --target=aarch64-linux-android$ANDROID_API --sysroot=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot ;" > $HOME/user-config.jam

      - name: Bootstrap Boost.Build
        working-directory: ./boost_1_83_0
        run: |
          set -e
          ./bootstrap.sh --with-toolset=clang

      - name: Build Boost for Android arm64-v8a
        working-directory: ./boost_1_83_0
        env:
          ANDROID_API: 21
          NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          set -e
          TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          SYSROOT="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
          ./b2 toolset=clang-android \
            cxxflags="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -std=c++14 -fvisibility=hidden" \
            linkflags="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -pie -Wl,--no-undefined -std=c++14" \
            target-os=android \
            address-model=64 \
            architecture=arm \
            abi=aapcs \
            binary-format=elf \
            threading=multi \
            threadapi=pthread \
            variant=release \
            link=static,shared \
            runtime-link=shared \
            --prefix=../boost_android_arm64_install \
            --build-dir=../boost_android_arm64_build \
            --layout=system \
            --user-config=$HOME/user-config.jam \
            --with-date_time \
            --with-filesystem \
            --with-log \
            --with-program_options \
            --with-regex \
            --with-serialization \
            --with-system \
            --with-thread \
            -d+2 install -j$(nproc)

      - name: Package Boost artifacts
        run: |
          set -e
          tar -czvf boost_android_arm64.tar.gz boost_android_arm64_install

      # --- TALLOC (self-healing, auto-repair, recovery logic) ---
      - name: Download and extract talloc
        run: |
          set -e
          wget https://www.samba.org/ftp/talloc/talloc-2.4.2.tar.gz -O talloc-2.4.2.tar.gz
          tar -xf talloc-2.4.2.tar.gz

      - name: Self-healing talloc build for Android/Ananbox (with verbose log)
        run: |
          #!/usr/bin/env bash
          set +e
          cd talloc-2.4.2

          # --- Function: auto-repair needed files/pkgs ---
          repair_file() {
            local filename="$1"
            local url="$2"
            if [ ! -f "$filename" ]; then
              echo "Восстанавливаем $filename из $url"
              wget "$url" -O "$filename"
              chmod +x "$filename" || true
            fi
          }

          # --- Function: ensure install dir and minimal structure ---
          ensure_install_dir() {
            if [ ! -d install ]; then
              echo "Создаём папку install"
              mkdir -p install/lib install/include
            fi
          }

          # --- Function: scan dir for critical files ---
          scan_critical_files() {
            echo "=== Файлы в $PWD ==="
            find . -type f \( -name 'waf*' -o -name 'configure' -o -name 'wscript' -o -name '*.c' -o -name '*.h' \)
          }

          # --- Step 1: Проверка и скачивание нужных файлов ---
          scan_critical_files | tee ../talloc_scan_step1.log

          repair_file "configure" "https://www.samba.org/ftp/talloc/talloc-2.4.2.tar.gz"
          if [ ! -f "waf-light" ]; then
            repair_file "waf-light" "https://www.samba.org/ftp/rsync/waf-light"
          fi

          # Если waf отсутствует, запускаем configure для генерации waf/waflib
          if [ ! -f "waf" ]; then
            if [ -f "configure" ]; then
              chmod +x configure
              ./configure || true
            fi
          fi

          # Если waf так и нет — качаем fallback waf
          if [ ! -f "waf" ]; then
            repair_file "waf" "https://waf.io/waf-2.0.25"
          fi

          # Если waflib нет — качаем и распаковываем waflib
          if [ ! -d "waflib" ]; then
            wget https://waf.io/waflib-2.0.25.zip -O waflib.zip
            unzip -q waflib.zip
            if [ -d waflib-2.0.25 ]; then mv waflib-2.0.25 waflib; fi
            if [ -d waflib ]; then echo "waflib восстановлен"; fi
          fi

          # --- Step 2: Удаление тестов и автопатчинг wscript ---
          echo "Удаляем тестовые исходники и патчим wscript" | tee ../talloc_patch.log
          find . -type f -name "test*.c" -delete || true
          find . -type d -name "test*" -exec rm -rf {} + || true
          if [ -f wscript ]; then
            sed -i '/def build_tests(ctx):/,/^$/d' wscript
            sed -i '/ctx\.recurse.*tests.*/d' wscript
            sed -i '/bld\.SAMBA_SUBSYSTEM.*tests.*/d' wscript
            sed -i '/tests\/Makefile/d' wscript
            sed -i '/tests = /d' wscript
            sed -i '/replace-test/d' wscript
            sed -i '/testsuite/d' wscript
            sed -i '/test_/d' wscript
          fi

          # --- Step 3: Сборка с автолечением ---
          export ANDROID_API=21
          export NDK_HOME="$HOME/android-ndk"
          export TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export SYSROOT="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
          export CC="$TOOLCHAIN/aarch64-linux-android$ANDROID_API-clang"
          export AR="$TOOLCHAIN/llvm-ar"
          export RANLIB="$TOOLCHAIN/llvm-ranlib"
          export CFLAGS="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -DANDROID -Wno-deprecated-declarations"
          export LDFLAGS="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC"

          ensure_install_dir

          build_ok=0
          for attempt in {1..3}; do
            echo "Попытка сборки talloc $attempt..." | tee -a ../talloc_build.log
            chmod +x waf
            ./waf configure \
              --disable-python \
              --without-gettext \
              --prefix=$PWD/install \
              CC="$CC" AR="$AR" RANLIB="$RANLIB" CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" 2>&1 | tee -a ../talloc_build.log
            ./waf build -v 2>&1 | tee -a ../talloc_build.log
            ./waf install 2>&1 | tee -a ../talloc_build.log
            # --- Проверяем наличие результата ---
            if [ -f install/lib/libtalloc.a ] || [ -f install/lib64/libtalloc.a ] || [ -d install ]; then
              echo "talloc успешно собран!"
              build_ok=1
              break
            else
              echo "Сборка не удалась, пробуем долечить..." | tee -a ../talloc_build.log
              scan_critical_files | tee -a ../talloc_build.log
              ensure_install_dir
              # если waflib или waf исчезли — восстанавливаем снова
              if [ ! -f waf ]; then repair_file "waf" "https://waf.io/waf-2.0.25"; fi
              if [ ! -d waflib ]; then
                wget https://waf.io/waflib-2.0.25.zip -O waflib.zip
                unzip -q waflib.zip
                if [ -d waflib-2.0.25 ]; then mv waflib-2.0.25 waflib; fi
              fi
              # если configure исчез — снова тянем tarball
              if [ ! -f configure ]; then wget https://www.samba.org/ftp/talloc/talloc-2.4.2.tar.gz -O talloc-repair.tar.gz; tar -xf talloc-repair.tar.gz --strip-components=1; fi
              # если install/lib нет — создаём
              ensure_install_dir
            fi
          done
          if [ $build_ok -ne 1 ]; then
            echo "Не удалось собрать talloc после 3 попыток, завершаем с ошибкой."
            scan_critical_files | tee -a ../talloc_build.log
            exit 1
          fi

      - name: Package talloc artifacts
        run: |
          set -e
          tar -czvf talloc_android_arm64.tar.gz -C talloc-2.4.2/install .

      - name: Upload talloc build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: talloc_build_logs
          path: |
            talloc_build.log
            talloc_patch.log
            talloc_scan_step1.log

      # --- PROOT ---
      - name: Clone proot
        run: |
          set -e
          git clone --depth=1 https://github.com/Ananbox/proot.git proot

      - name: Patch proot for Android bionic basename (show script in terminal and log)
        run: |
          set -e
          cd proot
          echo 'cat > basename_patch.h <<EOF
#ifdef __ANDROID__
#include <string.h>
static char *basename(const char *path) {
  char *last_slash = strrchr(path, \'/\');
  if (last_slash == NULL)
      return (char *)path;
  return last_slash + 1;
}
#else
#include <libgen.h>
#endif
EOF
sed -i "1r basename_patch.h" src/cli/cli.c
cat src/cli/cli.c | head -20
rm basename_patch.h
' | tee ../proot_patch_script.sh
          bash ../proot_patch_script.sh 2>&1 | tee ../proot_patch.log

      - name: Build proot for Android arm64-v8a (show in terminal and log)
        run: |
          set -e
          export ANDROID_API=21
          export NDK_HOME="$HOME/android-ndk"
          export TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
          export SYSROOT="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
          export CC="$TOOLCHAIN/aarch64-linux-android$ANDROID_API-clang"
          export AR="$TOOLCHAIN/llvm-ar"
          export RANLIB="$TOOLCHAIN/llvm-ranlib"
          export CFLAGS="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -I$PWD/../talloc-2.4.2/install/include -DANDROID -Wno-deprecated-declarations"
          export LDFLAGS="--target=aarch64-linux-android$ANDROID_API --sysroot=$SYSROOT -fPIC -L$PWD/../talloc-2.4.2/install/lib -ltalloc"
          cd proot/src
          {
            echo "=== make clean ==="
            make clean
            echo "=== make build ==="
            make V=1 CC="$CC" LD="$CC" STRIP=echo OBJCOPY=echo OBJDUMP=echo CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS"
            echo "=== copy result ==="
            cp -v proot $GITHUB_WORKSPACE/libproot.so
          } 2>&1 | tee ../../proot_build.log

      - name: Package proot artifacts
        run: |
          set -e
          tar -czvf proot_android_arm64.tar.gz libproot.so

      - name: Upload proot build and patch logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: proot_logs
          path: |
            proot_patch.log
            proot_patch_script.sh
            proot_build.log

      # --- FINAL ARTIFACTS ---
      - name: Upload Boost artifact
        uses: actions/upload-artifact@v4
        with:
          name: boost_android_arm64
          path: boost_android_arm64.tar.gz

      - name: Upload talloc artifact
        uses: actions/upload-artifact@v4
        with:
          name: talloc_android_arm64
          path: talloc_android_arm64.tar.gz

      - name: Upload proot artifact
        uses: actions/upload-artifact@v4
        with:
          name: proot_android_arm64
          path: proot_android_arm64.tar.gz
